import csv
from pathlib import Path

careers = {
"AI Engineer":["Python","Machine Learning","Deep Learning","TensorFlow","PyTorch","NumPy","Pandas","Computer Vision","NLP","Neural Networks"],
"Machine Learning Engineer":["Python","Machine Learning","Scikit-learn","TensorFlow","PyTorch","Feature Engineering","Model Deployment","MLOps","SQL","Git"],
"Data Scientist":["Python","Pandas","NumPy","Statistics","Machine Learning","SQL","Matplotlib","Seaborn","Jupyter","Feature Engineering"],
"Data Analyst":["Excel","SQL","Python","Pandas","Statistics","Power BI","Tableau","Data Visualization","Data Cleaning","Reporting"],
"AI Research Scientist":["Python","Deep Learning","Mathematics","Statistics","Research Methods","PyTorch","TensorFlow","NLP","Computer Vision","Scientific Writing"],
"Computer Vision Engineer":["Python","OpenCV","Computer Vision","PyTorch","TensorFlow","Image Processing","Object Detection","Image Segmentation","CNN","CUDA"],
"NLP Engineer":["Python","NLP","Transformers","BERT","GPT","PyTorch","TensorFlow","Text Classification","Tokenization","Embeddings"],
"Data Engineer":["Python","SQL","ETL","Apache Spark","Hadoop","Airflow","Kafka","Data Warehousing","AWS","Docker"],
"Big Data Engineer":["Python","Scala","Apache Spark","Hadoop","Kafka","Hive","HBase","ETL","Linux","Cloud Computing"],
"Cloud Engineer":["AWS","Azure","Google Cloud","Linux","Docker","Kubernetes","Terraform","Networking","Python","CI/CD"],
"DevOps Engineer":["Linux","Docker","Kubernetes","Jenkins","Git","CI/CD","Terraform","Ansible","AWS","Bash"],
"Site Reliability Engineer":["Linux","Kubernetes","Docker","Prometheus","Grafana","Python","Go","Terraform","Monitoring","Incident Management"],
"Backend Developer":["Python","Java","Node.js","SQL","REST API","GraphQL","PostgreSQL","MongoDB","Docker","Git"],
"Frontend Developer":["HTML","CSS","JavaScript","TypeScript","React","Angular","Vue.js","Git","Responsive Design","Web Accessibility"],
"Full Stack Developer":["HTML","CSS","JavaScript","React","Node.js","Python","SQL","MongoDB","REST API","Git"],
"Software Developer":["Python","Java","C++","JavaScript","Data Structures","Algorithms","Git","Testing","SQL","OOP"],
"Java Developer":["Java","Spring Boot","Maven","Gradle","Hibernate","JPA","SQL","REST API","JUnit","Git"],
"Python Developer":["Python","Django","Flask","FastAPI","SQL","REST API","Pytest","Git","Docker","OOP"],
"JavaScript Developer":["JavaScript","TypeScript","Node.js","React","Express.js","NPM","REST API","Git","HTML","CSS"],
"Mobile App Developer":["Kotlin","Java","Swift","Dart","Flutter","Android","iOS","React Native","REST API","Firebase"],
"Android Developer":["Kotlin","Java","Android SDK","Jetpack Compose","Gradle","Firebase","SQLite","REST API","Git","Material Design"],
"iOS Developer":["Swift","SwiftUI","Xcode","UIKit","Core Data","iOS SDK","REST API","Git","App Store Connect","Objective-C"],
"Flutter Developer":["Dart","Flutter","Firebase","REST API","Android","iOS","State Management","Git","SQLite","UI Design"],
"Cybersecurity Analyst":["Network Security","Linux","SIEM","Incident Response","Firewalls","Cryptography","Python","Threat Analysis","Vulnerability Assessment","SOC"],
"Security Engineer":["Cybersecurity","Network Security","Cloud Security","Firewalls","IDS","IPS","Linux","Python","SIEM","Identity Management"],
"Penetration Tester":["Ethical Hacking","Kali Linux","Metasploit","Burp Suite","Nmap","Wireshark","OWASP","Python","Web Security","Network Security"],
"Security Architect":["Security Architecture","Cloud Security","Zero Trust","Identity Management","Cryptography","Network Security","Risk Assessment","SIEM","Compliance","Threat Modeling"],
"Network Engineer":["TCP/IP","Routing","Switching","Cisco","BGP","OSPF","DNS","DHCP","VPN","Network Security"],
"Network Administrator":["Linux","Windows Server","TCP/IP","DNS","DHCP","Active Directory","Cisco","VPN","Firewalls","Network Monitoring"],
"Database Administrator":["SQL","MySQL","PostgreSQL","Oracle","SQL Server","Database Security","Backup","Replication","Performance Tuning","Linux"],
"Database Developer":["SQL","PL/SQL","MySQL","PostgreSQL","Oracle","Database Design","Stored Procedures","Triggers","Indexing","ETL"],
"Cloud Security Engineer":["AWS Security","Azure Security","IAM","Cloud Security","Terraform","Kubernetes Security","SIEM","Encryption","Zero Trust","Compliance"],
"Blockchain Developer":["Solidity","Ethereum","Smart Contracts","Web3.js","JavaScript","Cryptography","Blockchain","Hardhat","Git","DeFi"],
"Smart Contract Developer":["Solidity","Ethereum","Smart Contracts","Remix","Hardhat","OpenZeppelin","Web3.js","Testing","Cryptography","Blockchain"],
"Game Developer":["C#","C++","Unity","Unreal Engine","Game Physics","3D Modeling","Blender","Game Design","Shaders","Git"],
"Unity Developer":["C#","Unity","Game Physics","3D Graphics","Shaders","Animation","Blender","AR","VR","Git"],
"Unreal Engine Developer":["C++","Unreal Engine","Blueprints","Game Physics","3D Graphics","Shaders","Animation","Virtual Reality","Git","Level Design"],
"AR/VR Developer":["Unity","Unreal Engine","C#","C++","ARCore","ARKit","OpenXR","3D Modeling","Computer Vision","Blender"],
"Robotics Engineer":["Python","C++","ROS","Robotics","Computer Vision","Control Systems","Arduino","Raspberry Pi","Linux","MATLAB"],
"Embedded Systems Engineer":["C","C++","Microcontrollers","Embedded Linux","RTOS","Arduino","STM32","ARM","UART","SPI"],
"IoT Engineer":["Python","C","Arduino","Raspberry Pi","MQTT","IoT","Sensors","Embedded Systems","AWS IoT","Networking"],
"Firmware Engineer":["C","C++","Embedded Systems","Microcontrollers","RTOS","ARM","Debugging","UART","SPI","I2C"],
"Computer Engineer":["C","C++","Digital Logic","Computer Architecture","Operating Systems","Microprocessors","Embedded Systems","Python","Verilog","Linux"],
"Systems Engineer":["Linux","Windows Server","Networking","Python","PowerShell","Bash","Virtualization","Cloud Computing","Monitoring","Automation"],
"Linux Administrator":["Linux","Bash","Shell Scripting","Networking","SSH","Systemd","Docker","Ansible","Python","Security"],
"Windows Administrator":["Windows Server","PowerShell","Active Directory","Group Policy","DNS","DHCP","Microsoft Azure","Hyper-V","Security","Backup"],
"Solutions Architect":["Cloud Architecture","AWS","Azure","Networking","Microservices","Docker","Kubernetes","Security","Databases","System Design"],
"Enterprise Architect":["Enterprise Architecture","TOGAF","Cloud Computing","System Design","Business Architecture","Security","Integration","Governance","Strategy","Risk Management"],
"Software Architect":["System Design","Design Patterns","Microservices","Java","Python","Cloud Computing","APIs","Databases","Security","Scalability"],
"API Developer":["REST API","GraphQL","Python","Node.js","Java","OpenAPI","Postman","Authentication","SQL","Docker"],
"QA Engineer":["Software Testing","Test Automation","Selenium","Cypress","Playwright","Python","Java","API Testing","JIRA","Git"],
"Automation Test Engineer":["Selenium","Python","Java","Cypress","Playwright","Test Automation","API Testing","Jenkins","Git","CI/CD"],
"Performance Test Engineer":["JMeter","Load Testing","Performance Testing","SQL","Linux","Grafana","Prometheus","Python","Monitoring","Benchmarking"],
"DevSecOps Engineer":["DevOps","Cybersecurity","CI/CD","Docker","Kubernetes","Terraform","SAST","DAST","Git","Cloud Security"],
"Release Engineer":["CI/CD","Jenkins","Git","Docker","Kubernetes","Release Management","Linux","Automation","Version Control","Monitoring"],
"Build Engineer":["Maven","Gradle","CMake","Make","Jenkins","Git","Build Automation","Linux","Docker","CI/CD"],
"Technical Support Engineer":["Troubleshooting","Linux","Windows","Networking","SQL","Python","Customer Support","Ticketing Systems","Cloud Computing","Documentation"],
"IT Support Specialist":["Windows","Linux","Networking","Hardware Troubleshooting","Active Directory","Microsoft 365","Help Desk","DNS","DHCP","Security"],
"Systems Analyst":["Requirements Analysis","System Design","SQL","UML","Business Analysis","Documentation","Testing","Process Modeling","Python","Project Management"],
"Business Analyst":["Requirements Gathering","Business Analysis","SQL","Excel","UML","Process Modeling","Stakeholder Management","Documentation","JIRA","Data Analysis"],
"Product Manager":["Product Strategy","Roadmapping","Market Research","User Research","Agile","Scrum","Analytics","Stakeholder Management","Product Discovery","A/B Testing"],
"Product Analyst":["SQL","Excel","Product Analytics","Statistics","A/B Testing","Python","Tableau","Power BI","Data Visualization","User Behavior Analysis"],
"Project Manager":["Project Management","Agile","Scrum","JIRA","Risk Management","Scheduling","Budgeting","Leadership","Communication","Stakeholder Management"],
"Scrum Master":["Scrum","Agile","Sprint Planning","JIRA","Facilitation","Retrospectives","Conflict Resolution","Coaching","Team Management","Kanban"],
"UX Designer":["UX Design","User Research","Wireframing","Prototyping","Figma","Usability Testing","Information Architecture","Interaction Design","Design Thinking","Accessibility"],
"UI Designer":["UI Design","Figma","Adobe XD","Typography","Color Theory","Design Systems","Prototyping","Responsive Design","Visual Design","Accessibility"],
"UX Researcher":["User Research","Usability Testing","Interviews","Surveys","Qualitative Research","Quantitative Research","Personas","Journey Mapping","Figma","Data Analysis"],
"Graphic Designer":["Adobe Photoshop","Adobe Illustrator","InDesign","Typography","Branding","Illustration","Layout Design","Color Theory","Figma","Visual Design"],
"Data Visualization Specialist":["Tableau","Power BI","Python","Matplotlib","D3.js","Excel","Data Storytelling","SQL","Statistics","Dashboard Design"],
"BI Developer":["Power BI","Tableau","SQL","SSIS","SSRS","Data Warehousing","ETL","DAX","Excel","Data Modeling"],
"Analytics Engineer":["SQL","dbt","Python","Data Modeling","Data Warehousing","ETL","Git","Snowflake","BigQuery","Data Quality"],
"ML Operations Engineer":["MLOps","Docker","Kubernetes","MLflow","Python","CI/CD","AWS","Model Deployment","Monitoring","Terraform"],
"AI Product Manager":["AI","Product Management","Machine Learning","Product Strategy","User Research","Analytics","Roadmapping","A/B Testing","Stakeholder Management","Ethics"],
"Prompt Engineer":["Prompt Engineering","Large Language Models","NLP","Python","Generative AI","GPT","Embeddings","RAG","Evaluation","AI Safety"],
"Generative AI Engineer":["Python","Generative AI","LLMs","Transformers","PyTorch","RAG","Vector Databases","LangChain","Prompt Engineering","Model Evaluation"],
"LLM Engineer":["Python","LLMs","Transformers","PyTorch","Hugging Face","RAG","Fine-tuning","Embeddings","Vector Databases","Evaluation"],
"AI Solutions Architect":["AI Architecture","Machine Learning","Cloud Computing","Python","LLMs","MLOps","APIs","System Design","Security","Data Engineering"],
"Research Data Scientist":["Python","Statistics","Machine Learning","Research Methods","Pandas","NumPy","Data Visualization","Scientific Computing","SQL","Scientific Writing"],
"Quantitative Analyst":["Python","Statistics","Probability","Linear Algebra","Calculus","Machine Learning","Time Series","SQL","Financial Modeling","Optimization"],
"Financial Data Analyst":["Excel","SQL","Python","Statistics","Financial Modeling","Power BI","Tableau","Data Visualization","Forecasting","Accounting"],
"Financial Analyst":["Excel","Financial Modeling","Accounting","Financial Analysis","Forecasting","PowerPoint","SQL","Data Analysis","Budgeting","Valuation"],
"Risk Analyst":["Risk Management","Statistics","Excel","Python","SQL","Financial Modeling","Probability","Data Analysis","Compliance","Forecasting"],
"Operations Analyst":["Excel","SQL","Data Analysis","Statistics","Power BI","Process Improvement","Forecasting","Reporting","Python","Operations Research"],
"Marketing Analyst":["Excel","SQL","Google Analytics","Statistics","A/B Testing","Python","Tableau","Data Visualization","Market Research","SEO"],
"Digital Marketing Specialist":["SEO","SEM","Google Ads","Social Media Marketing","Content Marketing","Google Analytics","Email Marketing","WordPress","Copywriting","A/B Testing"],
"SEO Specialist":["SEO","Keyword Research","Google Search Console","Google Analytics","Technical SEO","Link Building","Content Strategy","HTML","CSS","Analytics"],
"Content Strategist":["Content Strategy","Copywriting","SEO","Content Marketing","Research","Social Media","Analytics","WordPress","Editing","Storytelling"],
"Technical Writer":["Technical Writing","Documentation","Markdown","Git","API Documentation","Research","Editing","Information Architecture","Diagrams","Communication"],
"DevRel Engineer":["Developer Relations","Technical Writing","Public Speaking","GitHub","APIs","Python","JavaScript","Community Management","Documentation","Content Creation"],
"Machine Vision Specialist":["Computer Vision","OpenCV","Python","Image Processing","Deep Learning","Object Detection","Image Segmentation","CUDA","PyTorch","TensorFlow"],
"Bioinformatics Scientist":["Python","R","Bioinformatics","Genomics","Statistics","Machine Learning","Data Analysis","Linux","SQL","Biostatistics"],
"Computational Biologist":["Python","R","Statistics","Machine Learning","Biology","Genomics","Data Analysis","Linux","Scientific Computing","Bioinformatics"],
"Healthcare Data Analyst":["SQL","Python","Statistics","Healthcare Analytics","Excel","Power BI","Data Visualization","HIPAA","Data Cleaning","Reporting"],
"GIS Analyst":["GIS","ArcGIS","QGIS","Python","SQL","Geospatial Analysis","Remote Sensing","Cartography","Spatial Databases","Data Visualization"],
"Geospatial Data Scientist":["Python","GIS","GeoPandas","QGIS","ArcGIS","Machine Learning","Remote Sensing","Spatial Analysis","SQL","Data Visualization"],
"Simulation Engineer":["MATLAB","Simulink","Python","C++","Numerical Methods","Modeling","Simulation","Control Systems","Statistics","Optimization"],
"Control Systems Engineer":["MATLAB","Simulink","Control Systems","PID Control","C++","Python","Signal Processing","Robotics","Embedded Systems","Optimization"],
"Electrical Engineer":["Circuit Design","MATLAB","Simulink","PCB Design","Embedded Systems","C","Power Electronics","Control Systems","Arduino","LTspice"],
"Electronics Engineer":["Circuit Design","PCB Design","Embedded Systems","C","Microcontrollers","Arduino","MATLAB","SPICE","Digital Electronics","Analog Electronics"],
"Mechanical Engineer":["CAD","SolidWorks","AutoCAD","MATLAB","Mechanical Design","Thermodynamics","Fluid Mechanics","Manufacturing","Finite Element Analysis","Engineering Drawing"],
"CAD Engineer":["AutoCAD","SolidWorks","CATIA","Creo","3D Modeling","CAD","Engineering Drawing","GD&T","Product Design","Manufacturing"],
"Manufacturing Engineer":["Lean Manufacturing","Six Sigma","CAD","CNC","Quality Control","Process Improvement","Manufacturing","Production Planning","Excel","ERP"],
"Quality Engineer":["Quality Control","Six Sigma","SPC","Root Cause Analysis","FMEA","ISO 9001","Lean Manufacturing","Excel","Auditing","Process Improvement"],
"Supply Chain Analyst":["Excel","SQL","Supply Chain Management","Inventory Management","Forecasting","Power BI","Data Analysis","Logistics","ERP","Optimization"],
"ERP Consultant":["SAP","Oracle ERP","ERP","SQL","Business Analysis","Process Mapping","Integration","Data Migration","Project Management","Testing"],
"SAP Consultant":["SAP","ABAP","SAP HANA","SQL","ERP","Business Process","Fiori","Data Migration","Integration","Testing"],
"Salesforce Developer":["Salesforce","Apex","SOQL","Lightning Web Components","JavaScript","REST API","Git","CRM","SQL","Testing"],
"CRM Analyst":["CRM","Salesforce","SQL","Excel","Customer Analytics","Data Analysis","Marketing Automation","Reporting","Power BI","Communication"],
"Database Engineer":["SQL","PostgreSQL","MySQL","Oracle","Database Design","Performance Tuning","Replication","Backup","Cloud Databases","Python"],
"Cloud Data Engineer":["AWS","Azure","Google Cloud","Python","SQL","Spark","Airflow","Kafka","Snowflake","Data Warehousing"],
"Snowflake Developer":["Snowflake","SQL","Python","Data Warehousing","ETL","dbt","AWS","Data Modeling","Performance Tuning","Git"],
"Azure Data Engineer":["Azure","Azure Data Factory","SQL","Python","Databricks","Synapse Analytics","Power BI","ETL","Data Warehousing","Git"],
"AWS Data Engineer":["AWS","S3","Glue","Redshift","Athena","Lambda","Python","SQL","Spark","Airflow"],
"GCP Data Engineer":["Google Cloud","BigQuery","Dataflow","Pub/Sub","Cloud Storage","Python","SQL","Spark","Airflow","Data Warehousing"],
"ETL Developer":["ETL","SQL","Python","SSIS","Talend","Informatica","Data Warehousing","Data Quality","Data Mapping","Git"],
"Data Architect":["Data Architecture","SQL","Data Modeling","Data Warehousing","Cloud Computing","Snowflake","BigQuery","AWS","Data Governance","ETL"],
"Data Governance Analyst":["Data Governance","Data Quality","Metadata Management","Data Catalog","SQL","Compliance","Privacy","Data Stewardship","Business Glossary","Reporting"],
"Privacy Engineer":["Data Privacy","Privacy by Design","GDPR","Encryption","Python","Cloud Security","Identity Management","Risk Assessment","Compliance","Data Governance"],
"AI Ethics Specialist":["AI Ethics","Responsible AI","Machine Learning","Bias Detection","Fairness","Privacy","AI Governance","Risk Assessment","Research Methods","Communication"],
"Technical Program Manager":["Program Management","Project Management","Agile","Risk Management","Roadmapping","Stakeholder Management","Technical Writing","Leadership","JIRA","Communication"],
"Engineering Manager":["Leadership","Software Engineering","Project Management","Agile","System Design","Hiring","Mentoring","Performance Management","Architecture","Communication"],
"Solutions Engineer":["Technical Sales","APIs","Cloud Computing","SQL","Python","Product Demonstration","Networking","System Design","Communication","Problem Solving"],
"Pre-Sales Engineer":["Technical Sales","Solution Architecture","Networking","Cloud Computing","APIs","Product Demonstration","Presentation","CRM","Requirements Analysis","Communication"],
"Site Reliability Analyst":["SRE","Monitoring","Linux","Python","Prometheus","Grafana","Incident Response","Kubernetes","Automation","Observability"],
"Observability Engineer":["Observability","Prometheus","Grafana","OpenTelemetry","Kubernetes","Linux","Python","Logging","Tracing","Monitoring"],
"Platform Engineer":["Kubernetes","Docker","Terraform","Linux","AWS","CI/CD","Python","Go","Git","Platform Engineering"],
"Cloud Platform Engineer":["Kubernetes","Terraform","AWS","Azure","Linux","Docker","CI/CD","Networking","Python","Cloud Architecture"],
"Distributed Systems Engineer":["Distributed Systems","Go","Java","Python","Kubernetes","Microservices","Kafka","Databases","Networking","System Design"],
"Systems Programmer":["C","C++","Rust","Linux","Operating Systems","Networking","Memory Management","Compilers","Debugging","Git"],
"Compiler Engineer":["C++","LLVM","Compilers","Parsing","C","Algorithms","Operating Systems","Assembly","Optimization","Debugging"],
"Embedded AI Engineer":["C++","Python","Embedded Systems","TensorFlow Lite","Edge AI","Computer Vision","Microcontrollers","Linux","PyTorch","Optimization"],
"Edge AI Engineer":["Python","C++","Edge AI","TensorFlow Lite","ONNX","Computer Vision","Embedded Linux","CUDA","Model Optimization","IoT"],
"Drone Software Engineer":["C++","Python","ROS","Computer Vision","Embedded Systems","PX4","ArduPilot","Control Systems","Linux","Robotics"],
"Autonomous Vehicle Engineer":["C++","Python","ROS","Computer Vision","Sensor Fusion","SLAM","Path Planning","Control Systems","Deep Learning","LiDAR"],
"Robotics Software Engineer":["C++","Python","ROS","Linux","Computer Vision","Motion Planning","SLAM","Control Systems","Git","Simulation"],
"Natural Language Researcher":["NLP","Python","Deep Learning","Transformers","PyTorch","Statistics","Research Methods","LLMs","Linguistics","Scientific Writing"],
"Computer Graphics Engineer":["C++","OpenGL","Vulkan","DirectX","Shaders","3D Graphics","Linear Algebra","Geometry","GPU Programming","Git"],
"Game AI Programmer":["C++","C#","Unity","Unreal Engine","Game AI","Pathfinding","Machine Learning","Behavior Trees","Game Physics","Algorithms"],
"Technical Artist":["Blender","Maya","Unity","Unreal Engine","3D Modeling","Shaders","Texturing","Python","Animation","VFX"],
"Motion Graphics Designer":["After Effects","Premiere Pro","Cinema 4D","Blender","Animation","Typography","Visual Effects","Storyboarding","Illustrator","Photoshop"],
"Video Editor":["Premiere Pro","DaVinci Resolve","After Effects","Video Editing","Color Grading","Audio Editing","Storytelling","Motion Graphics","Media Management","Exporting"],
"3D Artist":["Blender","Maya","3D Modeling","Texturing","Rigging","Animation","Lighting","Rendering","Substance Painter","ZBrush"],
"Cloud Solutions Consultant":["AWS","Azure","Google Cloud","Cloud Architecture","Networking","Security","Migration","Cost Optimization","Terraform","Communication"],
"IT Consultant":["IT Strategy","Cloud Computing","Cybersecurity","Business Analysis","Project Management","Networking","ERP","Data Analysis","Communication","Problem Solving"],
"Technology Consultant":["Technology Strategy","Cloud Computing","Software Architecture","Data Analytics","Cybersecurity","Digital Transformation","Project Management","Business Analysis","Communication","Leadership"],
"Digital Transformation Consultant":["Digital Transformation","Cloud Computing","Business Strategy","Data Analytics","AI","Automation","Project Management","Change Management","Agile","Communication"],
"Research Engineer":["Python","C++","Machine Learning","Deep Learning","Algorithms","Research Methods","Mathematics","Statistics","Scientific Computing","Technical Writing"],
"Applied Scientist":["Python","Machine Learning","Statistics","Deep Learning","Research Methods","Optimization","NLP","Computer Vision","Experimentation","Scientific Writing"],
"Algorithm Engineer":["Algorithms","Data Structures","C++","Python","Mathematics","Optimization","Graph Theory","Dynamic Programming","Complexity Analysis","Git"],
"Software Performance Engineer":["C++","Python","Profiling","Performance Optimization","Linux","Concurrency","Multithreading","Algorithms","Benchmarking","System Design"],
"Database Performance Engineer":["SQL","Database Optimization","Indexing","Query Tuning","PostgreSQL","Oracle","MySQL","Monitoring","Performance Testing","Linux"],
"FinTech Engineer":["Python","Java","SQL","Financial Technology","APIs","Microservices","Cloud Computing","Security","Data Analysis","Docker"],
"Blockchain Data Analyst":["SQL","Python","Blockchain Analytics","Ethereum","Data Visualization","Statistics","Dune Analytics","APIs","Data Cleaning","Excel"],
"AI Automation Engineer":["Python","Automation","APIs","LLMs","Generative AI","RPA","LangChain","Workflow Automation","Docker","Git"],
"RPA Developer":["UiPath","Automation Anywhere","Power Automate","Python","JavaScript","Process Automation","Excel","SQL","Workflow Design","API Integration"],
"Automation Engineer":["Python","Automation","Scripting","Selenium","Jenkins","Docker","Linux","APIs","CI/CD","Git"],
"Integration Engineer":["APIs","REST","GraphQL","Java","Python","MuleSoft","Integration Patterns","SQL","Cloud Computing","Docker"],
"Middleware Engineer":["Java","Spring","WebLogic","Tomcat","Kafka","REST API","Linux","Docker","SQL","Integration"],
"Message Queue Engineer":["Kafka","RabbitMQ","Redis","Python","Java","Distributed Systems","Linux","Docker","Microservices","Monitoring"],
"Search Engineer":["Elasticsearch","OpenSearch","Python","Java","SQL","Information Retrieval","NLP","Linux","Docker","APIs"],
"Recommendation Systems Engineer":["Python","Machine Learning","Recommender Systems","Statistics","Pandas","NumPy","TensorFlow","PyTorch","SQL","A/B Testing"],
"Speech AI Engineer":["Python","Speech Recognition","NLP","Deep Learning","PyTorch","TensorFlow","Audio Processing","Transformers","Signal Processing","Machine Learning"],
"AI Chatbot Developer":["Python","NLP","LLMs","RAG","LangChain","APIs","Prompt Engineering","Vector Databases","FastAPI","Docker"],
"Knowledge Engineer":["Knowledge Graphs","Ontology","NLP","Python","RDF","SPARQL","Semantic Web","Machine Learning","Data Modeling","Reasoning"],
"Data Quality Engineer":["Data Quality","Python","SQL","ETL","Data Validation","Great Expectations","Data Profiling","Data Governance","Testing","Airflow"],
"Data Reliability Engineer":["Data Engineering","Python","SQL","Airflow","Data Quality","Monitoring","Cloud Computing","ETL","Observability","Incident Response"],
"Data Platform Engineer":["Python","SQL","Kubernetes","Docker","Airflow","Spark","Kafka","Terraform","Cloud Computing","Data Warehousing"],
"Analytics Developer":["SQL","Python","Power BI","Tableau","dbt","Data Modeling","Excel","Statistics","Git","Data Visualization"],
"Reporting Analyst":["Excel","SQL","Power BI","Tableau","Reporting","Data Visualization","Statistics","Data Cleaning","Business Analysis","Communication"],
"Fraud Analyst":["Fraud Detection","SQL","Python","Statistics","Machine Learning","Risk Analysis","Data Analysis","Excel","Anomaly Detection","Reporting"],
"Fraud Data Scientist":["Python","Machine Learning","Fraud Detection","Statistics","SQL","Feature Engineering","Anomaly Detection","Scikit-learn","Pandas","Model Evaluation"],
"Actuarial Data Scientist":["Python","R","Statistics","Probability","Machine Learning","SQL","Excel","Risk Modeling","Time Series","Financial Mathematics"],
"Econometrician":["R","Python","Econometrics","Statistics","Regression","Time Series","SQL","Stata","Data Analysis","Mathematics"],
"Statistician":["R","Python","Statistics","Probability","Regression","Hypothesis Testing","Experimental Design","SQL","Data Visualization","Mathematics"],
"Operations Research Analyst":["Optimization","Linear Programming","Python","R","Statistics","Mathematics","Simulation","Excel","SQL","Decision Analysis"],
"Forecasting Analyst":["Time Series","Python","R","Statistics","Forecasting","ARIMA","Machine Learning","SQL","Excel","Data Visualization"],
"Market Research Analyst":["Market Research","Statistics","Survey Design","Excel","SQL","Data Analysis","Consumer Behavior","Data Visualization","SPSS","Communication"],
"Customer Data Analyst":["SQL","Python","Excel","Customer Analytics","Statistics","CRM","Power BI","Tableau","Segmentation","A/B Testing"],
"Product Designer":["Product Design","UX Design","UI Design","Figma","Prototyping","Design Systems","User Research","Interaction Design","Accessibility","Design Thinking"],
"Design Systems Designer":["Design Systems","Figma","UI Design","Typography","Accessibility","Components","Design Tokens","Prototyping","UX Design","Documentation"],
"Accessibility Specialist":["Web Accessibility","WCAG","HTML","CSS","JavaScript","ARIA","UX Design","Usability Testing","Accessibility Testing","Inclusive Design"],
"Web Accessibility Engineer":["HTML","CSS","JavaScript","WCAG","ARIA","React","Accessibility Testing","Screen Readers","Semantic HTML","Git"],
"Web Developer":["HTML","CSS","JavaScript","PHP","Python","React","Node.js","SQL","Git","Responsive Design"],
"WordPress Developer":["WordPress","PHP","HTML","CSS","JavaScript","MySQL","SEO","WooCommerce","Git","Web Hosting"],
"PHP Developer":["PHP","Laravel","Symfony","MySQL","JavaScript","HTML","CSS","REST API","Git","Docker"],
"Ruby Developer":["Ruby","Ruby on Rails","PostgreSQL","REST API","JavaScript","HTML","CSS","RSpec","Git","Docker"],
"Go Developer":["Go","Golang","Microservices","REST API","Docker","Kubernetes","Linux","Git","SQL","Concurrency"],
"Rust Developer":["Rust","Systems Programming","Cargo","Linux","C++","Memory Safety","WebAssembly","Networking","Git","Algorithms"],
"C++ Developer":["C++","STL","CMake","Multithreading","Linux","Algorithms","Data Structures","Git","Debugging","Object-Oriented Programming"],
"C Developer":["C","Pointers","Memory Management","Embedded Systems","Linux","GDB","Make","Git","Data Structures","Algorithms"],
"Scala Developer":["Scala","Apache Spark","Akka","Functional Programming","Java","Kafka","SQL","Git","Linux","Distributed Systems"],
"TypeScript Developer":["TypeScript","JavaScript","React","Node.js","Angular","NestJS","REST API","Git","HTML","CSS"],
"React Developer":["React","JavaScript","TypeScript","Redux","Next.js","HTML","CSS","REST API","Git","Jest"],
"Angular Developer":["Angular","TypeScript","RxJS","JavaScript","HTML","CSS","NgRx","REST API","Git","Jasmine"],
"Vue Developer":["Vue.js","JavaScript","TypeScript","Nuxt.js","HTML","CSS","Pinia","REST API","Git","Jest"],
"Node.js Developer":["Node.js","JavaScript","TypeScript","Express.js","NestJS","REST API","MongoDB","PostgreSQL","Git","Docker"],
"Django Developer":["Python","Django","Django REST Framework","PostgreSQL","HTML","CSS","JavaScript","REST API","Git","Docker"],
"FastAPI Developer":["Python","FastAPI","Pydantic","REST API","PostgreSQL","SQLAlchemy","Docker","Git","Pytest","OpenAPI"],
"API Integration Developer":["REST API","GraphQL","Python","Node.js","OAuth","JWT","Webhooks","Postman","SQL","Docker"],
"Microservices Engineer":["Microservices","Docker","Kubernetes","Java","Python","Go","REST API","Kafka","Service Mesh","Git"],
"Serverless Engineer":["AWS Lambda","Azure Functions","Google Cloud Functions","Python","Node.js","Serverless","API Gateway","DynamoDB","Terraform","Git"],
"Cloud Migration Engineer":["Cloud Migration","AWS","Azure","Google Cloud","Terraform","Docker","Kubernetes","Networking","Linux","Database Migration"],
"FinOps Analyst":["FinOps","AWS","Azure","Cloud Cost Management","Excel","SQL","Power BI","Cost Optimization","Budgeting","Reporting"],
"Cloud Network Engineer":["AWS Networking","Azure Networking","VPC","TCP/IP","Routing","VPN","DNS","Load Balancing","Firewalls","Terraform"],
"Identity and Access Engineer":["IAM","OAuth","SAML","OpenID Connect","Active Directory","Azure AD","AWS IAM","RBAC","Zero Trust","Cybersecurity"],
"DevOps Security Analyst":["DevSecOps","SAST","DAST","CI/CD","Container Security","Cloud Security","Git","Linux","Vulnerability Management","Python"],
"Threat Intelligence Analyst":["Threat Intelligence","Cybersecurity","OSINT","SIEM","Python","MITRE ATT&CK","Threat Analysis","Malware Analysis","Networking","Reporting"],
"Incident Response Analyst":["Incident Response","SIEM","Digital Forensics","Linux","Windows","Network Security","Python","Threat Hunting","Malware Analysis","Documentation"],
"Digital Forensics Analyst":["Digital Forensics","Autopsy","Volatility","Linux","Windows","Disk Analysis","Memory Forensics","Network Forensics","Python","Chain of Custody"],
"Malware Analyst":["Malware Analysis","Reverse Engineering","IDA Pro","Ghidra","Assembly","C","Python","Windows Internals","Debugging","Threat Analysis"],
"Security Operations Analyst":["SOC","SIEM","Incident Response","Threat Hunting","Networking","Linux","Windows","Python","MITRE ATT&CK","Security Monitoring"],
"Application Security Engineer":["Application Security","OWASP","SAST","DAST","Burp Suite","Threat Modeling","Secure Coding","Python","Java","CI/CD"],
"Cloud Compliance Analyst":["Cloud Compliance","AWS","Azure","GDPR","ISO 27001","SOC 2","Risk Assessment","Audit","Security Controls","Documentation"],
"Governance Risk Compliance Analyst":["GRC","Risk Management","Compliance","ISO 27001","SOC 2","GDPR","Audit","Security Controls","Policy Writing","Reporting"],
"Security Auditor":["Security Auditing","ISO 27001","SOC 2","Risk Assessment","Compliance","Vulnerability Assessment","Security Controls","Documentation","NIST","Reporting"],
"Network Security Engineer":["Network Security","Firewalls","IDS","IPS","VPN","Cisco","TCP/IP","SIEM","Python","Linux"],
"Firewall Engineer":["Firewalls","Cisco","Palo Alto","Fortinet","VPN","TCP/IP","Network Security","IDS","IPS","Linux"],
"Wireless Network Engineer":["Wi-Fi","Cisco","802.11","Networking","TCP/IP","RF Engineering","Wireless Security","Network Monitoring","Linux","Troubleshooting"],
"Telecommunications Engineer":["Telecommunications","5G","4G LTE","RF Engineering","Networking","Signal Processing","MATLAB","Python","Fiber Optics","Wireless"],
"RF Engineer":["RF Engineering","MATLAB","Signal Processing","Antenna Design","Microwave Engineering","5G","Wireless","Electromagnetics","Python","Simulation"],
"VLSI Engineer":["VLSI","Verilog","SystemVerilog","ASIC","FPGA","Digital Design","RTL","Cadence","Synopsys","Tcl"],
"FPGA Engineer":["FPGA","Verilog","VHDL","SystemVerilog","Digital Design","Xilinx","Intel Quartus","RTL","Embedded Systems","C"],
"ASIC Design Engineer":["ASIC","Verilog","SystemVerilog","RTL","Digital Design","Cadence","Synopsys","Physical Design","Tcl","Linux"],
"PCB Design Engineer":["PCB Design","Altium","KiCad","Eagle","Circuit Design","Signal Integrity","Power Integrity","CAD","Electronics","EMI/EMC"],
"Power Electronics Engineer":["Power Electronics","MATLAB","Simulink","Circuit Design","MOSFET","IGBT","Converters","Inverters","Control Systems","PCB Design"],
"Renewable Energy Engineer":["Solar Energy","Wind Energy","MATLAB","Simulink","Power Systems","Energy Storage","Grid Integration","Electrical Engineering","Data Analysis","Sustainability"],
"Energy Data Analyst":["Python","SQL","Excel","Power BI","Energy Analytics","Statistics","Forecasting","Data Visualization","Time Series","Reporting"],
"Environmental Data Scientist":["Python","R","Statistics","GIS","Machine Learning","Remote Sensing","Environmental Science","SQL","Data Visualization","Modeling"],
"Scientific Programmer":["Python","C++","NumPy","SciPy","Matplotlib","Linux","Git","Numerical Methods","Scientific Computing","Algorithms"],
"Computational Scientist":["Python","C++","Numerical Methods","HPC","Linux","MPI","CUDA","Scientific Computing","Mathematics","Simulation"],
"HPC Engineer":["Linux","C++","MPI","OpenMP","CUDA","HPC","Slurm","Python","Performance Optimization","Parallel Computing"],
"CUDA Developer":["CUDA","C++","GPU Programming","NVIDIA","Parallel Computing","Python","Linux","Optimization","Deep Learning","OpenCL"],
"Parallel Computing Engineer":["C++","MPI","OpenMP","CUDA","Parallel Computing","HPC","Algorithms","Linux","Performance Optimization","Python"],
"Mathematical Modeler":["Mathematics","Statistics","Python","MATLAB","Optimization","Differential Equations","Numerical Methods","Simulation","Linear Algebra","Modeling"],
"Optimization Engineer":["Optimization","Python","MATLAB","Linear Programming","Nonlinear Optimization","Algorithms","Mathematics","Simulation","OR-Tools","Gurobi"],
"Research Software Engineer":["Python","C++","Git","Linux","Scientific Computing","Software Engineering","Testing","Data Analysis","Research Methods","Documentation"],
"Academic Research Assistant":["Research Methods","Literature Review","Statistics","Python","R","Data Analysis","Scientific Writing","Presentation","Documentation","Critical Thinking"],
"Technical Trainer":["Training","Python","Java","Cloud Computing","Communication","Presentation","Curriculum Design","Technical Writing","Mentoring","Public Speaking"],
"Developer Advocate":["Developer Relations","Public Speaking","Technical Writing","GitHub","APIs","Cloud Computing","Community Management","Content Creation","Python","JavaScript"],
"Open Source Maintainer":["Git","GitHub","Python","JavaScript","Code Review","Issue Management","Documentation","CI/CD","Community Management","Software Development"],
"Software Configuration Manager":["Git","Version Control","CI/CD","Release Management","Jenkins","Configuration Management","Linux","Documentation","Automation","GitHub"],
"Configuration Engineer":["Ansible","Terraform","Git","Linux","Docker","Kubernetes","Configuration Management","Automation","Python","CI/CD"],
"Automation Architect":["Automation","Python","RPA","APIs","Cloud Computing","Workflow Automation","System Design","CI/CD","Docker","Security"],
"Integration Architect":["Integration Architecture","APIs","Microservices","REST","GraphQL","Kafka","Cloud Computing","Java","Security","System Design"],
"Data Integration Engineer":["ETL","APIs","SQL","Python","Kafka","Airflow","Data Warehousing","Cloud Computing","Data Mapping","Git"],
"Data Migration Specialist":["Data Migration","SQL","ETL","Python","Data Mapping","Data Validation","Oracle","PostgreSQL","Cloud Computing","Testing"],
"Master Data Management Analyst":["Master Data Management","Data Governance","SQL","Data Quality","Data Modeling","Data Stewardship","ETL","Business Analysis","Reporting","Excel"],
"Metadata Specialist":["Metadata Management","Data Catalog","SQL","Data Governance","Data Modeling","Data Quality","Documentation","Python","Business Glossary","Data Lineage"],
"Data Steward":["Data Governance","Data Quality","Metadata Management","Data Stewardship","SQL","Business Glossary","Compliance","Documentation","Data Privacy","Communication"],
"Knowledge Graph Engineer":["Knowledge Graphs","Python","RDF","SPARQL","Neo4j","Ontology","NLP","Graph Databases","Semantic Web","Data Modeling"],
"Graph Database Engineer":["Neo4j","Cypher","Graph Databases","Python","Java","Data Modeling","Graph Algorithms","SQL","Docker","APIs"],
"Search Relevance Engineer":["Information Retrieval","Elasticsearch","NLP","Python","Machine Learning","Ranking","Search Quality","A/B Testing","SQL","Statistics"],
"Data Labeling Specialist":["Data Annotation","Data Quality","Computer Vision","NLP","Machine Learning","Labeling Tools","Quality Assurance","Documentation","Attention to Detail","Data Management"],
"ML Data Engineer":["Python","SQL","ETL","Machine Learning","Feature Engineering","Data Pipelines","Airflow","Spark","Docker","Cloud Computing"],
"Feature Store Engineer":["Feature Engineering","Python","SQL","Feast","Machine Learning","Data Pipelines","Kubernetes","Docker","Cloud Computing","Git"],
"Model Validation Analyst":["Machine Learning","Statistics","Model Validation","Python","SQL","Risk Management","Model Evaluation","Data Analysis","Documentation","Excel"],
"AI Model Evaluator":["Machine Learning","LLMs","Evaluation","Python","Statistics","NLP","Data Analysis","Prompt Engineering","Benchmarking","Reporting"],
"AI Safety Engineer":["AI Safety","Machine Learning","LLMs","Python","Risk Assessment","Responsible AI","Red Teaming","Evaluation","Security","Research Methods"],
"AI Governance Analyst":["AI Governance","Responsible AI","Compliance","Risk Management","AI Ethics","Policy","Model Risk","Documentation","Data Privacy","Audit"],
"Responsible AI Engineer":["Responsible AI","Machine Learning","Fairness","Bias Detection","Explainable AI","Privacy","Python","Model Evaluation","AI Governance","Security"],
"Explainable AI Specialist":["Explainable AI","Machine Learning","Python","SHAP","LIME","Statistics","Model Interpretation","Data Visualization","Research Methods","Model Evaluation"],
"Reinforcement Learning Engineer":["Python","Reinforcement Learning","Deep Learning","PyTorch","TensorFlow","Probability","Optimization","Robotics","Simulation","Algorithms"],
"Deep Learning Engineer":["Python","Deep Learning","PyTorch","TensorFlow","Neural Networks","CNN","RNN","Transformers","GPU Computing","Mathematics"],
"Computer Vision Researcher":["Python","Computer Vision","Deep Learning","PyTorch","OpenCV","Image Processing","Object Detection","Image Segmentation","Research Methods","Mathematics"],
"Speech Recognition Engineer":["Python","Speech Recognition","NLP","PyTorch","TensorFlow","Audio Processing","Signal Processing","Deep Learning","Transformers","Machine Learning"],
"Time Series Scientist":["Python","Time Series","Statistics","Forecasting","Machine Learning","ARIMA","Prophet","Pandas","SQL","Data Visualization"],
"Experimentation Scientist":["A/B Testing","Statistics","Experimental Design","Python","SQL","Causal Inference","Data Analysis","Machine Learning","Product Analytics","R"],
"Causal Inference Scientist":["Causal Inference","Statistics","Python","R","Experimental Design","Econometrics","Machine Learning","SQL","Probability","Research Methods"],
"Machine Learning Researcher":["Python","Machine Learning","Deep Learning","Mathematics","Statistics","PyTorch","Research Methods","Algorithms","Optimization","Scientific Writing"],
"AI Research Engineer":["Python","PyTorch","TensorFlow","Deep Learning","Machine Learning","Research Methods","Algorithms","Optimization","NLP","Computer Vision"],
"Data Mining Engineer":["Python","SQL","Data Mining","Machine Learning","Statistics","Pandas","NumPy","Clustering","Classification","Association Rules"],
"Pattern Recognition Engineer":["Python","Machine Learning","Pattern Recognition","Computer Vision","NLP","Statistics","Deep Learning","Signal Processing","Scikit-learn","Mathematics"],
"Signal Processing Engineer":["MATLAB","Python","Signal Processing","DSP","Fourier Transform","Control Systems","C++","Embedded Systems","Statistics","Mathematics"],
"Image Processing Engineer":["Python","OpenCV","Image Processing","MATLAB","Computer Vision","Deep Learning","NumPy","C++","Signal Processing","Linear Algebra"],
"Audio Engineer":["Audio Processing","DSP","Python","MATLAB","Signal Processing","Acoustics","Pro Tools","Ableton Live","Mixing","Mastering"],
"Game Tools Engineer":["C++","C#","Unity","Unreal Engine","Python","Game Development","Tools Programming","Git","Automation","3D Graphics"],
"Graphics Programmer":["C++","OpenGL","Vulkan","DirectX","Shaders","GPU Programming","Linear Algebra","3D Graphics","HLSL","GLSL"],
"Rendering Engineer":["C++","OpenGL","Vulkan","DirectX","Ray Tracing","Shaders","GPU Programming","Graphics Algorithms","Linear Algebra","Git"],
"AR Engineer":["Unity","C#","ARCore","ARKit","Computer Vision","3D Graphics","SLAM","OpenXR","Python","Git"],
"VR Engineer":["Unity","C#","OpenXR","VR","3D Graphics","Game Physics","Unreal Engine","Blender","Interaction Design","Git"],
"Metaverse Developer":["Unity","Unreal Engine","C#","3D Modeling","Blockchain","Web3","VR","AR","JavaScript","Blender"],
"Digital Twin Engineer":["IoT","Python","3D Modeling","Simulation","Digital Twins","Cloud Computing","CAD","Data Analytics","Unity","APIs"],
"Industrial IoT Engineer":["IoT","PLC","SCADA","MQTT","Python","C++","Sensors","Industrial Networking","Cloud Computing","Cybersecurity"],
"SCADA Engineer":["SCADA","PLC","HMI","Industrial Automation","Modbus","OPC UA","Networking","C","Control Systems","Cybersecurity"],
"PLC Programmer":["PLC","Ladder Logic","Siemens","Allen-Bradley","HMI","SCADA","Industrial Automation","Control Systems","Electrical Engineering","Troubleshooting"],
"Automation Controls Engineer":["PLC","Control Systems","MATLAB","Simulink","Industrial Automation","Robotics","Sensors","C++","SCADA","PID Control"],
"Mechatronics Engineer":["Mechanical Engineering","Electrical Engineering","Robotics","Control Systems","CAD","MATLAB","Arduino","C++","Sensors","Embedded Systems"],
"Biomedical Engineer":["Biomedical Engineering","MATLAB","Python","Signal Processing","Medical Devices","Biology","CAD","Data Analysis","Electronics","Biostatistics"],
"Medical Imaging Scientist":["Medical Imaging","Python","MATLAB","Image Processing","Computer Vision","MRI","CT","Deep Learning","Signal Processing","Statistics"],
"Health Informatics Analyst":["Health Informatics","SQL","Python","Healthcare Analytics","Data Visualization","Electronic Health Records","Statistics","Data Governance","Reporting","Excel"],
"Clinical Data Analyst":["Clinical Data","SQL","Python","Statistics","Clinical Research","Data Cleaning","SAS","Excel","Data Visualization","Documentation"],
"Pharmaceutical Data Scientist":["Python","R","Statistics","Machine Learning","Pharmaceutical Analytics","Clinical Data","SQL","Data Visualization","Bioinformatics","Research Methods"],
"Computational Chemistry Scientist":["Python","R","Chemistry","Molecular Modeling","Machine Learning","Scientific Computing","Statistics","Linux","Data Analysis","Simulation"],
"Climate Data Scientist":["Python","R","Climate Science","Statistics","Machine Learning","GIS","Remote Sensing","Time Series","Data Visualization","Scientific Computing"],
"Remote Sensing Analyst":["Remote Sensing","GIS","Python","QGIS","ArcGIS","Image Processing","Satellite Imagery","Machine Learning","Geospatial Analysis","SQL"],
"Urban Data Scientist":["Python","GIS","SQL","Statistics","Urban Analytics","Machine Learning","Data Visualization","Geospatial Analysis","R","Transportation Modeling"],
"Transportation Data Analyst":["Python","SQL","GIS","Statistics","Transportation Analytics","Excel","Power BI","Forecasting","Data Visualization","Optimization"],
"Logistics Data Scientist":["Python","SQL","Machine Learning","Optimization","Supply Chain","Forecasting","Statistics","Data Visualization","Operations Research","Excel"],
"Business Intelligence Analyst":["SQL","Power BI","Tableau","Excel","Data Analysis","Data Visualization","DAX","Statistics","Reporting","Business Analysis"],
"Customer Success Analyst":["SQL","Excel","Customer Analytics","CRM","Power BI","Data Visualization","Retention Analysis","Cohort Analysis","Communication","Reporting"],
"Growth Analyst":["SQL","Python","A/B Testing","Product Analytics","Statistics","Marketing Analytics","Cohort Analysis","Funnel Analysis","Excel","Data Visualization"],
"Revenue Analyst":["Excel","SQL","Revenue Management","Forecasting","Statistics","Pricing Analytics","Power BI","Data Visualization","Financial Analysis","Reporting"],
"Pricing Analyst":["Excel","SQL","Pricing Strategy","Statistics","Python","Forecasting","Revenue Management","Data Analysis","Optimization","Power BI"],
"Business Intelligence Developer":["SQL","Power BI","Tableau","DAX","Data Modeling","ETL","SSIS","Data Warehousing","Python","Git"],
"Data Warehouse Engineer":["SQL","Data Warehousing","Snowflake","Redshift","BigQuery","ETL","Dimensional Modeling","Python","dbt","Cloud Computing"],
"Lakehouse Engineer":["Databricks","Delta Lake","Apache Spark","Python","SQL","Data Engineering","Data Warehousing","AWS","Azure","Data Governance"],
"Databricks Engineer":["Databricks","Apache Spark","Python","SQL","Delta Lake","PySpark","Data Engineering","MLflow","Azure","AWS"],
"Spark Engineer":["Apache Spark","PySpark","Scala","Python","SQL","Kafka","Hadoop","Data Engineering","Linux","Cloud Computing"],
"Kafka Engineer":["Apache Kafka","Java","Python","Kafka Streams","Distributed Systems","Docker","Kubernetes","Linux","Microservices","Monitoring"],
"Airflow Engineer":["Apache Airflow","Python","SQL","DAGs","ETL","Docker","Kubernetes","AWS","Data Pipelines","Git"],
"ETL Architect":["ETL","Data Architecture","Data Warehousing","SQL","Python","Cloud Computing","Data Modeling","Data Governance","Integration","System Design"],
"Data Pipeline Engineer":["Python","SQL","Airflow","Spark","Kafka","ETL","Docker","Kubernetes","Cloud Computing","Data Quality"],
"DataOps Engineer":["DataOps","Python","SQL","Airflow","Docker","Kubernetes","CI/CD","Data Quality","Monitoring","Git"],
"ML Platform Engineer":["MLOps","Kubernetes","Docker","Python","MLflow","Terraform","AWS","CI/CD","Model Serving","Monitoring"],
"Model Deployment Engineer":["Python","Docker","Kubernetes","FastAPI","MLflow","Model Serving","AWS","CI/CD","Machine Learning","Monitoring"],
"AI Infrastructure Engineer":["Linux","Python","CUDA","Kubernetes","Docker","GPU Computing","Cloud Computing","MLOps","Networking","Terraform"],
"GPU Computing Engineer":["CUDA","C++","GPU Programming","NVIDIA","Parallel Computing","Linux","Python","OpenCL","Performance Optimization","Deep Learning"],
"Cloud AI Engineer":["AWS","Azure","Google Cloud","Python","Machine Learning","Deep Learning","MLOps","Docker","Kubernetes","LLMs"],
"AI Data Scientist":["Python","Machine Learning","Deep Learning","Statistics","Pandas","NumPy","SQL","Feature Engineering","Model Evaluation","Visualization"],
"Business AI Analyst":["AI","Business Analysis","Python","SQL","Machine Learning","Excel","Power BI","Statistics","Process Improvement","Communication"],
"AI Consultant":["AI Strategy","Machine Learning","Generative AI","Cloud Computing","Python","Business Analysis","Product Strategy","Responsible AI","Communication","Project Management"],
"Machine Learning Consultant":["Machine Learning","Python","Statistics","Cloud Computing","MLOps","Data Science","Model Deployment","Business Analysis","Communication","Project Management"],
"Data Science Consultant":["Python","Machine Learning","Statistics","SQL","Data Visualization","Business Analysis","Cloud Computing","Communication","Project Management","Presentation"],
"Cloud Consultant":["AWS","Azure","Google Cloud","Cloud Architecture","Networking","Security","Terraform","Migration","Cost Optimization","Communication"],
"Cybersecurity Consultant":["Cybersecurity","Risk Assessment","Network Security","Cloud Security","Compliance","Penetration Testing","SIEM","Incident Response","Communication","Project Management"],
"Software Testing Consultant":["Software Testing","Test Automation","Selenium","API Testing","Performance Testing","Agile","JIRA","Python","Java","Communication"],
"Agile Coach":["Agile","Scrum","Kanban","Coaching","Facilitation","Leadership","Communication","Conflict Resolution","Lean","Change Management"],
"Technical Project Manager":["Project Management","Software Development","Agile","Scrum","JIRA","Risk Management","Stakeholder Management","System Design","Leadership","Communication"],
"Program Analyst":["Excel","SQL","Data Analysis","Project Management","Reporting","Power BI","Statistics","Process Improvement","Communication","Documentation"],
"IT Business Analyst":["Business Analysis","SQL","Excel","Requirements Gathering","UML","Process Modeling","JIRA","Stakeholder Management","Documentation","Testing"],
"Process Improvement Analyst":["Lean","Six Sigma","Process Improvement","Excel","Data Analysis","Business Analysis","Root Cause Analysis","Process Mapping","Power BI","Statistics"],
"Management Consultant":["Business Strategy","Data Analysis","Financial Modeling","Market Research","Project Management","PowerPoint","Excel","Problem Solving","Communication","Leadership"],
"Strategy Analyst":["Business Strategy","Market Research","Excel","PowerPoint","Data Analysis","Financial Modeling","Competitive Analysis","SQL","Statistics","Communication"],
"Technology Strategy Analyst":["Technology Strategy","Cloud Computing","Data Analytics","AI","Cybersecurity","Business Analysis","Financial Modeling","Market Research","PowerPoint","Communication"],
"Technical Recruiter":["Technical Recruiting","Software Engineering","AI/ML","Cloud Computing","LinkedIn","Interviewing","Communication","Sourcing","ATS","Employer Branding"],
"Developer Productivity Engineer":["Developer Experience","Git","CI/CD","Automation","Python","Go","Kubernetes","Docker","Developer Tools","Monitoring"],
"Internal Tools Engineer":["Python","JavaScript","React","APIs","SQL","Docker","Git","Automation","Internal Tools","Cloud Computing"],
"Developer Experience Engineer":["Developer Experience","APIs","GitHub","CI/CD","Python","JavaScript","Documentation","Automation","Developer Tools","Cloud Computing"],
"API Platform Engineer":["APIs","Kubernetes","Docker","Python","Go","REST","GraphQL","API Gateway","Security","Cloud Computing"],
"Service Mesh Engineer":["Kubernetes","Istio","Envoy","Microservices","Networking","Docker","Linux","Observability","Security","Go"],
"Container Security Engineer":["Docker","Kubernetes","Container Security","Linux","Trivy","SAST","DAST","Cloud Security","CI/CD","Python"],
"Kubernetes Engineer":["Kubernetes","Docker","Helm","Linux","Terraform","Prometheus","Grafana","CI/CD","Networking","Git"],
"Terraform Engineer":["Terraform","AWS","Azure","Google Cloud","Infrastructure as Code","Git","Python","Kubernetes","Cloud Security","CI/CD"],
"Ansible Engineer":["Ansible","Linux","Python","YAML","Automation","Configuration Management","AWS","Docker","Git","CI/CD"],
"Jenkins Engineer":["Jenkins","CI/CD","Groovy","Git","Docker","Kubernetes","Linux","Automation","Python","DevOps"],
"Observability Architect":["Observability","OpenTelemetry","Prometheus","Grafana","Logging","Tracing","Monitoring","Kubernetes","Cloud Computing","SRE"],
"Monitoring Engineer":["Prometheus","Grafana","Nagios","Zabbix","Linux","Python","Monitoring","Alerting","Networking","Cloud Computing"],
"Production Engineer":["Linux","Python","SQL","Monitoring","Incident Response","Automation","Docker","Kubernetes","SRE","Debugging"],
"Reliability Engineer":["SRE","Linux","Kubernetes","Monitoring","Incident Response","Automation","Python","Cloud Computing","Reliability Engineering","Observability"],
"Capacity Planning Analyst":["Capacity Planning","Statistics","Excel","Python","Forecasting","Performance Testing","Cloud Computing","SQL","Data Analysis","Modeling"],
"Performance Engineer":["Performance Optimization","Profiling","C++","Java","Python","Linux","Benchmarking","Concurrency","Databases","Monitoring"],
"Scalability Engineer":["Scalability","Distributed Systems","Kubernetes","Microservices","Cloud Computing","Databases","Caching","Load Balancing","Performance Testing","System Design"],
"Storage Engineer":["Storage Systems","Linux","SAN","NAS","Cloud Storage","Backup","Replication","Networking","Python","Monitoring"],
"Backup Engineer":["Backup","Disaster Recovery","Linux","Windows Server","Cloud Storage","Veeam","AWS","Azure","Automation","Security"],
"Disaster Recovery Engineer":["Disaster Recovery","Business Continuity","Cloud Computing","Backup","Linux","AWS","Azure","Risk Assessment","Automation","Testing"],
"Business Continuity Analyst":["Business Continuity","Risk Management","Disaster Recovery","Business Impact Analysis","ISO 22301","Project Management","Documentation","Communication","Testing","Compliance"],
"IT Risk Analyst":["IT Risk Management","Cybersecurity","Compliance","Risk Assessment","NIST","ISO 27001","Audit","Excel","Reporting","Controls"],
"Technology Risk Consultant":["Technology Risk","Cybersecurity","Cloud Security","Risk Assessment","Compliance","IT Audit","NIST","ISO 27001","Governance","Communication"],
"Model Risk Analyst":["Model Risk Management","Statistics","Machine Learning","Python","Risk Management","Model Validation","Excel","SQL","Documentation","Governance"],
"Credit Risk Analyst":["Credit Risk","Financial Analysis","Statistics","Python","SQL","Excel","Probability","Machine Learning","Risk Modeling","Reporting"],
"Investment Data Analyst":["Python","SQL","Excel","Financial Data","Statistics","Data Visualization","Bloomberg","Financial Modeling","Power BI","Research"],
"FinTech Data Scientist":["Python","SQL","Machine Learning","Statistics","Financial Data","Risk Modeling","Time Series","Pandas","Cloud Computing","APIs"],
"Quant Developer":["Python","C++","Quantitative Finance","Algorithms","Statistics","Probability","SQL","Linux","Financial Modeling","Git"],
"Algorithmic Trading Developer":["Python","C++","Algorithms","Quantitative Finance","Time Series","Statistics","Low Latency","Linux","APIs","Data Analysis"],
"Trading Systems Engineer":["C++","Python","Low Latency","Linux","Networking","Distributed Systems","Financial Markets","Algorithms","SQL","Git"],
"Financial Software Engineer":["Java","Python","C++","SQL","Financial Systems","APIs","Microservices","Cloud Computing","Docker","Git"],
"EdTech Software Engineer":["Python","JavaScript","React","Node.js","SQL","APIs","Cloud Computing","Docker","Git","Education Technology"],
"Education Data Analyst":["Python","SQL","Excel","Statistics","Power BI","Data Visualization","Learning Analytics","Reporting","Data Cleaning","Communication"],
"Learning Analytics Scientist":["Python","R","Statistics","Machine Learning","Learning Analytics","SQL","Data Visualization","A/B Testing","Education Data","Research Methods"],
"Speech and Language Scientist":["Linguistics","NLP","Python","Statistics","Speech Processing","Machine Learning","Phonetics","Corpus Analysis","Research Methods","Scientific Writing"],
"Computational Linguist":["Python","NLP","Linguistics","Machine Learning","Statistics","Transformers","Corpus Linguistics","Text Mining","Research Methods","SQL"],
"Language Model Researcher":["Python","Deep Learning","Transformers","LLMs","PyTorch","NLP","Mathematics","Statistics","Research Methods","Scientific Writing"],
"AI Dataset Curator":["Data Curation","Data Quality","Python","SQL","Machine Learning","Data Annotation","Metadata","Data Governance","Documentation","NLP"],
"Data Annotation Lead":["Data Annotation","Data Quality","Team Management","Computer Vision","NLP","Project Management","Quality Assurance","Documentation","Training","Reporting"],
"ML Technical Writer":["Technical Writing","Machine Learning","Python","Documentation","Markdown","Git","API Documentation","Research","Editing","Communication"],
"AI Documentation Engineer":["Technical Writing","AI","Machine Learning","Python","API Documentation","Markdown","Git","Information Architecture","Documentation","Editing"],
}

# Deduplicate skills globally while keeping original spelling.
rows = [(career, skill) for career, skills in careers.items() for skill in dict.fromkeys(skills)]

out = Path("career_skills.csv")
with out.open("w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["career", "skill"])
    writer.writerows(rows)

unique_skills = sorted({skill for _, skill in rows}, key=str.lower)
len(careers), len(rows), len(unique_skills), out.stat().st_size
